### ISSUE TITLE
PHP 7.4

### ISSUE THREAD

**Issue by traderjean** [PayXpert/connect2pay-php-client#1]
Hello, it crashes with PHP 7.4 because Array and string offset access syntax with curly braces is deprecated. Can you fix this ? Thanks

**Comment by zainab-o** [comment]
Hi!, please replace {} with [] because its deprecated in php 7.4

![image](https://user-images.githubusercontent.com/72856911/102773686-f41c2d80-4389-11eb-8ad3-dd7b3304c972.png)

**Comment by holajsh** [comment]
Fixed in v2.70.0
